# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da2e02ec085721d522e10aebc6bc562332f06528575f2d8fb9f717c2357afeff18348e09555bc5b64adbeec945a861fbbea67117aa53b63db4e5fda46dd0775a

test:
  secret_key_base: e545538e2d5ae771450943da270fd1e1bb83fa28f2005ef1fcf7cac63ffe770f1b7418e6a3f2ebf647a21946989ce90872748b7a80f41c6335fe1e26bc5be917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
